#ifndef __DEFINES_H__
#define __DEFINES_H__

#define RWBIT(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
#define WNIBBLE(WORD,STARTBITPOS,NIBBLE) WORD=((WORD&~(15<<STARTBITPOS))|(NIBBLE<<STARTBITPOS))
#define WRITENIBBLE(WORD,STARTBITPOS,NIBBLE) WORD=((WORD&~(15<<STARTBITPOS))|(NIBBLE<<STARTBITPOS))
#define RNIBBLE(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&15)
#define READNIBBLE(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&15)
#define CPLBIT(WORD,BIT) (WORD^=1<<BIT)
#define SETBIT(WORD,BIT) (WORD|=1<<BIT)
#define SSETBIT(WORD,BIT) (WORD=1<<BIT)
#define CLRBIT(WORD,BIT) (WORD&=~(1<<BIT))
#define SCLRBIT(WORD,BIT) (WORD=1<<BIT)
#define WRITEBIT(WORD,BIT,BITLEVEL) WORD=(WORD&=~(1<<BIT))|(BITLEVEL<<BIT)
#define WRITEBYTE(WORD,BIT,BYTE) WORD=((WORD&~(255<<BIT))|(BYTE<<BIT)) 
#define READBIT(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&1)

#endif

